export const ADDONE = "ADDONE"
export const REMOVEONE = "REMOVEONE"
export const ADDTOW  = "ADDTOW"
export const REMOVETOW = "REMOVETOW"
export const LOGLOG = "LOGLOG"
export const PUSHDATA = "PUSHDATA"